// Code generated by entc, DO NOT EDIT.

package passwords

import (
	"time"
)

const (
	// Label holds the string label denoting the passwords type in the database.
	Label = "passwords"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// EdgeCred holds the string denoting the cred edge name in mutations.
	EdgeCred = "cred"
	// Table holds the table name of the passwords in the database.
	Table = "passwords"
	// CredTable is the table that holds the cred relation/edge.
	CredTable = "passwords"
	// CredInverseTable is the table name for the Creds entity.
	// It exists in this package in order to avoid circular dependency with the "creds" package.
	CredInverseTable = "creds"
	// CredColumn is the table column denoting the cred relation/edge.
	CredColumn = "creds_passwords"
)

// Columns holds all SQL columns for passwords fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldPassword,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "passwords"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"creds_passwords",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)
